FROM postgres:15.2

RUN apt-get update && apt-get  install -y postgresql-15-postgis-3

COPY *.sql ./sql/create_tables.sql/docker-entrypoint-initdb.d/

CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]